### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Kiohey124** [GeekyGhost/Automatic1111-Geeky-Remb#2]
Hi, I wanted to try the extension but it doesn't work, I read the thread for a possible solution but I didn't find anything, I don't know if I'm missing a file or it's a problem with my PC. I get that code
![Captura de pantalla 2024-08-20 162245](https://github.com/user-attachments/assets/0683d7dc-af61-4987-bef0-546b0a26373c)

**Comment by GeekyGhost** [comment]
Thanks for reaching out, can you send me the error? I did an update right
before it got listed to add features someone requested so I may have missed
some dependencies.

**Comment by GeekyGhost** [comment]
Ah yeah, that's exactly what happened. Updated the requirements so it should work now.
