### ISSUE TITLE
GeekyRemb doesn't load models from the default models folder

### ISSUE THREAD

**Issue by arzyu** [GeekyGhost/Automatic1111-Geeky-Remb#5]
Instead, it retrieves the model from C:\Users\xxx\.u2net, which caused my system to download duplicate files.
Am I using it incorrectly, or is there a parameter available to set the model path?

**Comment by GeekyGhost** [comment]
Oops, nope, that's on me. I have all my GUIs pulling from personal folders
so I'm not downloading models for each one. This is counter productive for
others, give me a day and I'll fix it. This is on me and my bad for setting
it up so I can be lazy.

**Comment by GeekyGhost** [comment]
Okay, should be all set.

**Comment by GeekyGhost** [comment]
Should be resolved, it now uses the unet model folder inside of auto/forge
